-- Nova - storico prezzi pacchetti per mese di competenza
-- Eseguire nel progetto Supabase "Orchidea Allievi", dove risiede iscrizioni_corsi.

create table if not exists public.nova_package_pricing_history (
  id bigint generated by default as identity primary key,
  enrollment_id text not null,
  tesseramento_id text not null,
  corso_id text,
  effective_from date not null,
  quota_allievo_mensile numeric(12,2) not null default 0,
  pacchetto_nome text,
  pacchetto_totale_mensile numeric(12,2),
  note_pacchetto text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nova_package_pricing_history_unique unique (enrollment_id, effective_from)
);

create index if not exists idx_nova_package_pricing_history_student
  on public.nova_package_pricing_history (tesseramento_id, effective_from);

create index if not exists idx_nova_package_pricing_history_enrollment
  on public.nova_package_pricing_history (enrollment_id, effective_from);

alter table public.nova_package_pricing_history enable row level security;

drop policy if exists "nova_package_pricing_history_select" on public.nova_package_pricing_history;
create policy "nova_package_pricing_history_select"
  on public.nova_package_pricing_history
  for select
  to authenticated
  using (auth.uid() is not null);

drop policy if exists "nova_package_pricing_history_insert" on public.nova_package_pricing_history;
create policy "nova_package_pricing_history_insert"
  on public.nova_package_pricing_history
  for insert
  to authenticated
  with check (auth.uid() is not null);

drop policy if exists "nova_package_pricing_history_update" on public.nova_package_pricing_history;
create policy "nova_package_pricing_history_update"
  on public.nova_package_pricing_history
  for update
  to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

drop policy if exists "nova_package_pricing_history_delete" on public.nova_package_pricing_history;
create policy "nova_package_pricing_history_delete"
  on public.nova_package_pricing_history
  for delete
  to authenticated
  using (auth.uid() is not null);

-- Fotografa lo stato attuale come baseline dalla data di inizio dell'iscrizione.
-- Questo rende stabile lo storico precedente alla prima modifica con la nuova versione di Nova.
insert into public.nova_package_pricing_history (
  enrollment_id,
  tesseramento_id,
  corso_id,
  effective_from,
  quota_allievo_mensile,
  pacchetto_nome,
  pacchetto_totale_mensile,
  note_pacchetto
)
select
  i.id::text,
  i.tesseramento_id::text,
  i.corso_id::text,
  coalesce(i.data_inizio, i.data_iscrizione, i.created_at::date, current_date),
  greatest(coalesce(i.quota_allievo_mensile, i.tariffa_mensile, c.prezzo_mensile, 0), 0),
  i.pacchetto_nome,
  i.pacchetto_totale_mensile,
  i.note_pacchetto
from public.iscrizioni_corsi i
left join public.corsi c on c.id = i.corso_id
where i.tesseramento_id is not null
on conflict (enrollment_id, effective_from) do nothing;

notify pgrst, 'reload schema';
